name: Deploy on Push/Merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Deploy latest and greatest
        uses: appleboy/ssh-actions@master
        with:
          host: testare.itdev.ro
          username: testare
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/testare/htdocs/testare.itdev.ro
            git pull origin main
