name: Deploy on Push/Merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Change to project directory
        run: cd /home/testare/htdocs/testare.itdev.ro/
      - name: Pull latest changes
        run: git pull origin main
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
