name: Deploy on Push/Merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          key: ${{ secret.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/testare/htdocs/testare.itdev.ro
            git pull origin main
