name: Deploy on Merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy to remote server
        run: |
          ssh testare@testare.itdev.ro "cd /home/testare/htdocs/testarea.itdev.ro/ && git pull origin main"
        env: SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
